version: '3'

services:
  backend:
    build: ./backend
    ports:
      - '3333:3333' # Porta do backend Fastify
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - '5173:5173' # Porta do frontend Vite
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development

  prisma:
    image: prismagraphql/prisma:1.34
    command: prisma studio
    ports:
      - '5555:5555' # Porta do Prisma Studio
    volumes:
      - ./backend/prisma:/app/prisma
    depends_on:
      - backend

  db:
    image: mongo:latest
    ports:
      - '27017:27017' # Porta do MongoDB
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
